name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v3
      with:
        node-version: 10.x
        cache: npm
    - run: npm ci
    - run: npm install -g resume-cli@1.2.8
    - run: npm install --no-save @percy/script
    - run: npm run build:styles
    - run: resume serve --resume=example-resume.json --port 5001 --silent &
    - run: sleep 2s
    - run: npx percy exec -- node tests/percy.js
